#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

_git_clone_or_pull "$install_dir/appstore"
_git_clone_or_pull "$install_dir/apps" https://github.com/YunoHost/apps.git
_git_clone_or_pull "$install_dir/apps_tools" https://github.com/YunoHost/apps-tools.git

ynh_config_add --template="update_catalog.sh" --destination="$install_dir/update_catalog.sh"
chmod +x "$install_dir/update_catalog.sh"

# Fixture until we manage it properly
ln -s "$install_dir/apps" "$install_dir/appstore/.cache/apps"
ln -s "$install_dir/apps_cache" "$install_dir/appstore/.apps_cache"

chown -R "$app:www-data" "$install_dir"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

pushd "$install_dir/apps_tools" > /dev/null
{
    _update_venv
    ynh_exec_as_app venv/bin/pip install -r requirements.txt > /dev/null
}
popd > /dev/null

ynh_script_progression "Downloading apps and appstore cache..."
ynh_exec_as_app "$install_dir/update_catalog.sh"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --log="/var/log/$app/$app.log"

# Add cron job
cron_path="/etc/cron.d/$app"
ynh_config_add --template="task.cron" --destination="$cron_path"
chown root: "$cron_path"
chmod 644 "$cron_path"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
